pizzeria/p_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pizzeria.urls")),
]

pizzeria/pizzeria/urls.py
"""pizzeriaのURLパターンの定義"""

from django.urls import path

from . import views

app_name = "pizzeria"
urlpatterns = [
    # ホームページ
    path("", views.index, name="index"),
    path("pizzas/", views.pizzas, name="pizzas"),
    path("pizzas/<int:pizza_id>/", views.pizza, name="pizza"),
]

pizzeria/pizzeria/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

pizzeria/pizzeria/views.py
from django.shortcuts import render

from .models import Pizza


def index(request):
    return render(request, "pizzeria/index.html")


def pizzas(request):
    pizzas = Pizza.objects.order_by("date_added")
    context = {"pizzas": pizzas}
    return render(request, "pizzeria/pizzas.html", context)


def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by("-date_added")
    context = {"pizza": pizza, "toppings": toppings}
    return render(request, "pizzeria/pizza.html", context)

pizzeria/pizzeria/templates/pizzeria/base.html
<p>
  <a href="{% url 'pizzeria:index' %}">商品一覧</a> -
  <a href="{% url 'pizzeria:pizzas' %}">ピザ一覧</a>
</p>

{% block content %}{% endblock content%}

pizzeria/pizzeria/templates/pizzeria/index.html
{% extends "pizzeria/base.html" %} {% block content %}
<p>わたしたちのお店のピザを紹介します！</p>

{% endblock content %}

pizzeria/pizzeria/templates/pizzeria/pizza.html
{% extends "pizzeria/base.html" %} {% block content %}

<p>ピザ: {{ pizza.name }}</p>

<p>トッピング:</p>
<ul>
  {% for topping in toppings %}
  <li>
    <p>{{ topping.name|linebreaks }}</p>
  </li>
  {% empty %}
  <li>この商品にはトッピングがまだ登録されていません。</li>
  {% endfor %}
</ul>

{% endblock content %}

pizzeria/pizzeria/templates/pizzeria/pizzas.html
as{% extends "pizzeria/base.html" %} {% block content %}

<p>ピザ一覧</p>

<ul>
  {% for pizza in pizzas %}
  <li>
    <a href="{% url 'pizzeria:pizza' pizza.id %}"> {{ pizza.name }}</a>
  </li>
  {% empty %}
  <li>商品はまだ登録されていません。</li>
  {% endfor %}
</ul>

{% endblock content %}