learning_log/accounts/urls.py
"""accounts用URLパターンの定義"""

from django.urls import include, path

from . import views

app_name = "accounts"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
]

learning_log/learning_logs/urls.py
"""learning_logsのURLパターンの定義"""

from django.urls import path

from . import views

app_name = "learning_logs"
urlpatterns = [
    path("", views.index, name="index"),
    path("topics/", views.topics, name="topics"),
    path("topics/<int:topic_id>/", views.topic, name="topic"),
    path("new_topic/", views.new_topic, name="new_topic"),
    path("new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),
]

learning_log/ll_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("learning_logs.urls")),
]

learning_log/accounts/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        if len(self.text) >= 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

learning_log/learning_logs/forms.py
from django import forms

from .models import Entry, Topic


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

learning_log/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("learning_logs:index")

    context = {"form": form}
    return render(request, "registration/register.html", context)

learning_log/learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render

from .forms import EntryForm, TopicForm
from .models import Entry, Topic


def index(request):
    return render(request, "learning_logs/index.html")


@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request.user)
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)


@login_required
def new_topic(request):
    if request.method != "POST":
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect("learning_logs:topics")

    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)


@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request.user)
    if request.method != "POST":
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect("learning_logs:topic", topic_id=topic_id)

    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/new_entry.html", context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(topic, request.user)
    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("learning_logs:topic", topic_id=topic.id)

    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, "learning_logs/edit_entry.html", context)


def check_topic_owner(topic, user):
    if topic.owner != user:
        raise Http404

learning_log/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>学習ノート</title>

    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
          学習ノート</a
        >

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="ナビゲーションの切り替え"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-mb-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                トピック一覧</a
              >
            </li>
          </ul>
          <!--　navbar左側のリンクリストの終了　-->

          <!-- アカウント関連のリング -->
          <ul class="navbar-nav ms-auto mb-2 mb-md-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2"
                >こんにちは {{ user.username }}さん
              </span>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                ユーザー登録</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">
                ログイン</a
              >
            </li>
            {% endif %}
          </ul>
          <!-- アカウント関連のリンクの終了 -->

          {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button name="submit" class="btn btn-outline-secondary btn-sm">
              ログアウト
            </button>
          </form>
          {% endif %}
        </div>
        <!-- navbarの折りたたみ可能なパーツの終了 -->
      </div>
      <!-- navbarコンテナの終了 -->
    </nav>
    <!-- navbar全体の終了　-->

    <main class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}
        <div class="p-3 mb-4 bg-light border rounded-3">
          <div class="container-fluid py-4">
            <h1 class="display-3">学んだことを記録しよう</h1>

            <p class="lead">
              自分だけの学習ノートを作成して、学んだことをいつでも振り返れるようにしよう。<br />
              何か新しいことを学んだら、その内容を要約した記事を書こう。
            </p>

            <a
              class="btn btn-primary btn-lg mt-1"
              href="{% url 'accounts:register' %}"
              >登録する &raquo;</a
            >
          </div>
        </div>

        {% endblock %}
      </div>
      <div>{% block content %}{% endblock %}</div>
    </main>
  </body>
</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %} {% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>記事を編集:</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
  {% csrf_token %} {{ form.as_div }}
  <button name="submit">記事を更新</button>
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %} {% block content %}
<p>
  学習ノートを使えば、好みのトピックについて学習していることを
  記録して、いつも最新の状態を把握できます。
</p>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %} {% block content%}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>新しい記事を追加:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
  {% csrf_token %} {{ form.as_div }}
  <button nama="submit">記事を追加</button>
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %} {% block content %}
<p>新規トピックを追加:</p>

<form action="{% url 'learning_logs:new_topic' %}" method="post">
  {% csrf_token %} {{ form.as_div }}
  <button name="submit">トピックを追加</button>
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %} {% block content %}

<p>トピック: {{ topic.text }}</p>

<p>記事:</p>
<p>
  <a href="{% url 'learning_logs:new_entry' topic.id %}">新しい記事を追加</a>
</p>
<ul>
  {% for entry in entries %}
  <li>
    <p>{{ entry.data_added|date:"Y年m月d日 H:i" }}</p>
    <p>{{ entry.text|linebreaks }}</p>
    <p>
      <a href="{% url 'learning_logs:edit_entry' entry.id %}">記事を編集</a>
    </p>
  </li>

  {% empty %}
  <li>このトピックにはまだ記事がありません。</li>
  {% endfor %}
</ul>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>トピック一覧</p>

  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url "learning_logs:topic" topic.id %}">
            {{ topic.text }}</a>
        </li>
    {% empty %}
      <li>トピックはまだ作成されていません。</p>
    {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topic' %}">新規トピックを追加</a>

{% endblock content %}