Blog/accounts/urls.py
from django.urls import include, path

from . import views

app_name = "accounts"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
]

Blog/b_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("blogs.urls")),
]

Blog/blogs/urls.py
"""blogsのURLパターンの定義"""

from django.urls import path

from . import views

app_name = "blogs"
urlpatterns = [
    path("", views.index, name="index"),
    path("blogs/", views.blogs, name="blogs"),
    path("blogs/<int:blog_id>/", views.blog, name="blog"),
    path("new_blog/", views.new_blog, name="new_blog"),
    path("new_entry/<int:blog_id>/", views.new_entry, name="new_entry"),
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),
]

Blog/accounts/models.py
from django.db import models

# Create your models here.

Blog/blogs/models.py
from django.contrib.auth.models import User
from django.db import models


class Blog(models.Model):
    text = models.CharField(max_length=200)
    data_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(self.text) >= 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

Blog/blogs/forms.py
from django import forms

from .models import Blog, Entry


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ["text"]
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

Blog/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("blogs:index")

    context = {"form": form}
    return render(request, "registration/register.html", context)

Blog/blogs/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render

from .forms import BlogForm, EntryForm
from .models import Blog, Entry


def index(request):
    return render(request, "blogs/index.html")


def blogs(request):
    blogs = Blog.objects.order_by("data_added")
    context = {"blogs": blogs}
    return render(request, "blogs/blogs.html", context)


def blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    entries = blog.entry_set.order_by("-date_added")
    context = {"blog": blog, "entries": entries}
    return render(request, "blogs/blog.html", context)


def new_blog(request):
    if request.method != "POST":
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("blogs:blogs")

    context = {"form": form}
    return render(request, "blogs/new_blog.html", context)


@login_required
def new_entry(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    check_blog_owner(blog, request.user)
    if request.method != "POST":
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.blog = blog
            new_entry.save()
            return redirect("blogs:blog", blog_id=blog_id)

    context = {"blog": blog, "form": form}
    return render(request, "blogs/new_entry.html", context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    blog = entry.blog
    check_blog_owner(blog, request.user)
    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("blogs:blog", blog_id=blog.id)

    context = {"entry": entry, "blog": blog, "form": form}
    return render(request, "blogs/edit_entry.html", context)


def check_blog_owner(blog, user):
    if blog.owner != user:
        raise Http404

Blog/blogs/templates/blogs/base.html
<p>
  <a href="{% url 'blogs:index' %}">ブログ</a> -
  <a href="{% url 'blogs:blogs' %}">ブログ一覧</a>
  {% if user.is_authenticated %} こんにちは {{ user.username }}さん {% else %}
  <a href="{% url 'accounts:register' %}">ユーザー登録</a>
  <a href="{% url 'accounts:login' %}">ログイン</a>
  {% endif %}
</p>

{% block content %}{% endblock content%} {% if user.is_authenticated %}
<hr />
<form action="{% url 'accounts:logout' %}" method="post">
  {% csrf_token %}
  <button name="submit">ログアウト</button>
</form>
{% endif %}

Blog/blogs/templates/blogs/blog.html
{% extends "blogs/base.html" %} {% block content %}

<p>ブログ: {{ blog.text }}</p>

<p>記事:</p>
<p>
  <a href="{% url 'blogs:new_entry' blog.id %}">新しい記事を追加</a>
</p>

<ul>
  {% for entry in entries %}
  <li>
    <p>{{ entry.data_added|date:'Y年m月d日 H:i' }}</p>
    <p>{{ entry.text|linebreaks }}</p>
    <p>
      <a href="{% url 'blogs:edit_entry' entry.id %}">記事を編集<a/>
  </li>
  {% empty %}
  <li>このブログにはまだ記事がありません。</li>
  {% endfor %}
</ul>

{% endblock content %}

Blog/blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %} {% block content %}

<p>ブログ一覧</p>

<ul>
  {% for blog in blogs %}
  <li>
    <a href="{% url 'blogs:blog' blog.id %}"> {{ blog.text }}</a>
  </li>
  {% empty %}
  <li>トピックはまだ作成されていません。</li>
  {% endfor %}
</ul>

<a href="{% url "blogs:new_blog" %}">新規ブログを追加</a>

{% endblock content %}

Blog/blogs/templates/blogs/edit_entry.html
{% extends "blogs/base.html" %} {% block content %}

<p><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>

<p>記事を編集:</p>

<form action="{% url 'blogs:edit_entry' entry.id %}" method="post">
  {% csrf_token %} {{ form.as_div }}
  <button name="submit">記事を更新</button>
</form>

{% endblock content %}

Blog/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %} {% block content %}
<p>日々の出来事をブログに記録しましょう！</p>

{% endblock content %}

Blog/blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %} {% block content %}
<p>新規ブログを追加:</p>

<form action="{% url 'blogs:new_blog' %}" method="post">
  {% csrf_token %} {{ form.as_div }}
  <button name="submit">ブログを追加</button>
</form>

{% endblock content %}

Blog/blogs/templates/blogs/new_entry.html
{% extends "blogs/base.html" %} {% block content%}

<p><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>

<p>新しい記事を追加:</p>
<form action="{% url 'blogs:new_entry' blog.id %}" method="post">
  {% csrf_token %} {{ form.as_div }}
  <button nama="submit">記事を追加</button>
</form>

{% endblock content %}